### ISSUE TITLE
Create the ruledefs table by reading in sql/ruledefs.csv

### ISSUE THREAD

**Issue by bokov** [cattolyst/datafinisher#19]
Right now, the rule definitions table is hardcoded into `sqldump.cfg`. This is a temporary thing, just so the rest of `makesql.py` will run. 

To resolve this ticket, the `sql/ruledefs.csv` file needs to be read in and inserted into the `ruledefs` table (probably using `cnx.executemany()`). The reason for doing it this way is that it will be easier to edit and understand individual rules and parts of rules in a CSV file than as a raw SQL script as it currently is.

In the future, there will be some default values filling in the `NULL`s so that the sysadmin won't have to copy-paste stuff that is identical to existing rules-- they will only need to specify the stuff that's different. Storing rules in a CSV file also sets the stage for this, and possibly other programmatic manipulation of custom rules.

**Comment by bokov** [comment]
Found a stackexchange post that does this in a tidy manner: http://stackoverflow.com/a/2888042/945039

**Comment by bokov** [comment]
Here's another one: http://stackoverflow.com/questions/12136850/tab-delimited-file-using-csv-reader-not-delimiting-where-i-expect-it-to

**Comment by cattolyst** [comment]
I think the main lesson learned from here is if the csv file is reading in weirdly with inconsistent column numbers for each row, we just have to use skipinitialspace dialect in csv.reader (note: you can also use this in csv.DictReader)
