### ISSUE TITLE
how do I get one-row-per-patient output?

### ISSUE THREAD

**Issue by dckc** [cattolyst/datafinisher#30]

**Comment by bokov** [comment]
Please file future issues on https://github.com/UTHSCSA-CIRD/datafinisher 
That is the new active branch.

In answer to your question, by doing either of two things:
- Insuring that the data you select only has one observation per patient (This may still fail if you have only one observation per patient per data element, but those observations happen on different dates. If so, see below). 
- Setting the `-d` flag large enough that the entire patient's history for each data element will get squished into one row. By default, `-d` is set to 1 (day). If you set it to, say, 1000, that should do the trick. This will average all numeric values over that time period and do delimited concatenation on all code values (or return a Yes/No if you're using the `-s` option)

The more generic answer is, you should not be throwing away data unless you really thought through the analysis strategy and can document good reasons why this will not bias your interpretation.
