### ISSUE TITLE
Factor all/most of the functions and lengthy SQL snippets into separate files.

### ISSUE THREAD

**Issue by bokov** [cattolyst/datafinisher#7]
There is already emerging a consistent structure to the code: dynamic SQL for generating the `select` part of the table creation statement, more dynamic SQL for generating the `join`s, a few snippets of code for gluing the above together into SQL commands that create those respective tables, some static SQL for creating rules, some more static SQL for creating rule-specific views, if needed.

To make the code more readable and maintainable, to set the stage for a generic rule-executing function, and to also set the stage for an external configuration file, we need to factor out all the SQL out into another file that this script imports, and only handles variables declared in that file instead of lengthy string literals.

**Comment by bokov** [comment]
Good job, cattolyst! Your factor branch is exactly what I wanted. Now, see if you can similarly move all the custom functions except main() into a separate file. Not into the config file of course; I believe this time the Pythonic way is to use import, but please check for yourself-- first teh intarnets and if they don't help, post on StackExchange, and if nobody answers, ask bos666 to answer.

**Comment by bokov** [comment]
Addendum: factoring out functions is kind of a separate task than factoring out long string variables, so it should get its own branch off of `master`. This branch will _not_ have the variable changes you just made, and that's okay-- you don't need the variable changes to implement the function changes.

Also, you may find that there are multiple approaches to importing functions from another file. Go with whichever one pulls in all the functions at once without having to explicitly choose each one and doesn't require you to use `.` when invoking them later on.

**Comment by bokov** [comment]
Oops, I declared mission accomplished on the variable refactoring too soon. The variable refactor needs to be tested. You will find at least two problems:
- If the strings are imported into a dictionary, they cannot be referenced as local variables. I.e. `cnx.execute(cdid_tab)` will not work. It and all expressions like it should have the form `cnx.execute(par['cdid_tab'])`.
- Something about the way the variables are quoted or escaped in sqldump.cfg is causing errors. If you copy-paste the contents into a single-quoted string, they suddenly start to work. Might want to look into the possibility that you don't have to triple-quote strings in sqldump.cfg (since it's not a Python script, it's a config file).

**Comment by bokov** [comment]
Okay, commit ac8e35192c on `factor` branch fixes the quoting problem, and `master` is in sync with it as well. However, the `par['FOO']` way of referencing variables still needs to be done throughout `makesql.py`

Either that or explicitly declaring each `FOO = par['FOO']` at the beginning.

**Comment by bokov** [comment]
I have merged the `newddict` branch into `master`, so the feature branch for properly referencing the variables from the configuration file can be forked off from there now.

**Comment by cattolyst** [comment]
okay, so I'm going to ignore the note I made to create a 'newfactor' branch from 'newdict'.
I'm just going to pull from master and continue factoring out the SQL.
EDIT: Just kidding. I'll be creating 'newfactor' from 'master'.
